# ============================================================
# ESTADOS DE CONVERSACIÓN
# ============================================================

# Estados globales para conversaciones
(
    ESPERANDO_PASSWORD,
    ESPERANDO_CANTIDAD_PREGUNTAS,
    ESPERANDO_PREGUNTAS_TEXTO,
    ESPERANDO_FORMATO_LOTES,
    ESPERANDO_TIEMPO_LOTES,
    ESPERANDO_RESPUESTAS_PREGUNTA,
    ESPERANDO_OPCIONES,
    ESPERANDO_CORRECTAS,
    ESPERANDO_RESPUESTA_ABIERTA,
    ESPERANDO_IMAGENES,
    ESPERANDO_VIDEOS,
    ESPERANDO_ENLACES,
    ESPERANDO_CONFIRMACION,
    ESPERANDO_CSV,
    ESPERANDO_LANZAR_NOMBRE,
    ESPERANDO_LANZAR_CANTIDAD,
    ESPERANDO_LANZAR_SELECCION,
    ESPERANDO_LANZAR_FIJAS,
    ESPERANDO_LANZAR_FILTRO,
    ESPERANDO_LANZAR_TIEMPO,
    ESPERANDO_LANZAR_REINTENTOS,
    ESPERANDO_HISTORIAL_TIPO,
    ESPERANDO_LIMPIAR_HISTORIAL,
    ESPERANDO_CONFIGURACION,
    ESPERANDO_RESPUESTA_ABIERTA_TEXTO,
    ESPERANDO_LANZAR_CONFIRMAR,
    ESPERANDO_ELIMINAR_PREGUNTA,   # <--- AGREGAR ESTA LÍNEA
) = range(27)  # <--- CAMBIAR DE 26 A 27